/*******************************************************/
/*      This file is automatically generated           */
/*        !!! DO NOT MODIFY THIS FILE !!!              */
/*        All changes will be overwritten              */
/*******************************************************/

#ifndef _OBJTAB_H_
#define _OBJTAB_H_

// Object ID list
#define CNT_CONTAINER2 2 // CONTAINER2
#define CNT_DASHCONT 1 // DASHCONT
#define CNT_VELCHEICONS_1 0 // VELCHEICONS_1
#define MSK_MASK0 0 // MASK0
#define MSK_MASK1 1 // MASK1
#define MSK_MASK2 2 // MASK2
#define MSK_MASK3 3 // MASK3
#define OBJ_A_POS_BG_0 30 // A_POS_BG_0
#define OBJ_BAT_CURR_BAR 73 // BAT_CURR_BAR
#define OBJ_BAT_DISCHARG_BAR 75 // BAT_DISCHARG_BAR
#define OBJ_CURRENT 2 // CURRENT
#define OBJ_DISCHARGE_CAP_VAL 5 // DISCHARGE_CAP_VAL
#define OBJ_DISCHARGE_CAP_VAL_1 77 // DISCHARGE_CAP_VAL_1
#define OBJ_DISCHARGE_CAP_VAL_2 102 // DISCHARGE_CAP_VAL_2
#define OBJ_DISCHARGE_POWER_VAL 0 // DISCHARGE_POWER_VAL
#define OBJ_DISCHARGE_POWER_VAL_1 31 // DISCHARGE_POWER_VAL_1
#define OBJ_FON 68 // FON
#define OBJ_FORGND 70 // FORGND
#define OBJ_FUEL_AROW 71 // FUEL_AROW
#define OBJ_HI_VOLTAGE_VAL 4 // HI_VOLTAGE_VAL
#define OBJ_HI_VOLTAGE_VAL_1 79 // HI_VOLTAGE_VAL_1
#define OBJ_ICOINDX_10 42 // ICOINDX_10
#define OBJ_ICOINDX_11 43 // ICOINDX_11
#define OBJ_ICOINDX_12 44 // ICOINDX_12
#define OBJ_ICOINDX_13 45 // ICOINDX_13
#define OBJ_ICOINDX_14 46 // ICOINDX_14
#define OBJ_ICOINDX_15 47 // ICOINDX_15
#define OBJ_ICOINDX_16 48 // ICOINDX_16
#define OBJ_ICOINDX_17 49 // ICOINDX_17
#define OBJ_ICOINDX_18 50 // ICOINDX_18
#define OBJ_ICOINDX_19 51 // ICOINDX_19
#define OBJ_ICOINDX_20 52 // ICOINDX_20
#define OBJ_ICOINDX_21 53 // ICOINDX_21
#define OBJ_ICOINDX_22 54 // ICOINDX_22
#define OBJ_ICOINDX_23 55 // ICOINDX_23
#define OBJ_ICOINDX_24 56 // ICOINDX_24
#define OBJ_INDEXBITMAP22 22 // INDEXBITMAP22
#define OBJ_INDEXBITMAP23 23 // INDEXBITMAP23
#define OBJ_INV_CURR_BAR 74 // INV_CURR_BAR
#define OBJ_INV_VOLT_BAR 76 // INV_VOLT_BAR
#define OBJ_LOW_VOLTAGE_VAL 13 // LOW_VOLTAGE_VAL
#define OBJ_LOW_VOLTAGE_VAL_1 78 // LOW_VOLTAGE_VAL_1
#define OBJ_PRESS_AROW 72 // PRESS_AROW
#define OBJ_RPM_AROW 65 // RPM_AROW
#define OBJ_SIMPLEBITMAP75 66 // SIMPLEBITMAP75
#define OBJ_SIMPLEBITMAP92 69 // SIMPLEBITMAP92
#define OBJ_SPD_AROW 67 // SPD_AROW
#define OBJ_TEXT 6 // TEXT
#define OBJ_TEXT_1 7 // TEXT_1
#define OBJ_TEXT_10 87 // TEXT_10
#define OBJ_TEXT_11 88 // TEXT_11
#define OBJ_TEXT_12 89 // TEXT_12
#define OBJ_TEXT_13 90 // TEXT_13
#define OBJ_TEXT_14 101 // TEXT_14
#define OBJ_TEXT_2 8 // TEXT_2
#define OBJ_TEXT_3 9 // TEXT_3
#define OBJ_TEXT_4 10 // TEXT_4
#define OBJ_TEXT_5 11 // TEXT_5
#define OBJ_TEXT_6 12 // TEXT_6
#define OBJ_TEXT_7 84 // TEXT_7
#define OBJ_TEXT_8 85 // TEXT_8
#define OBJ_TEXT_9 86 // TEXT_9
#define OBJ_TRUETYPETEXT33 33 // TRUETYPETEXT33
#define OBJ_TRUETYPETEXT34 34 // TRUETYPETEXT34
#define OBJ_TRUETYPETEXT35 35 // TRUETYPETEXT35
#define OBJ_TRUETYPETEXT36 36 // TRUETYPETEXT36
#define OBJ_UNIT 14 // UNIT
#define OBJ_UNIT_1 15 // UNIT_1
#define OBJ_UNIT_10 93 // UNIT_10
#define OBJ_UNIT_11 94 // UNIT_11
#define OBJ_UNIT_12 103 // UNIT_12
#define OBJ_UNIT_2 16 // UNIT_2
#define OBJ_UNIT_3 17 // UNIT_3
#define OBJ_UNIT_4 18 // UNIT_4
#define OBJ_UNIT_5 19 // UNIT_5
#define OBJ_UNIT_6 20 // UNIT_6
#define OBJ_UNIT_7 32 // UNIT_7
#define OBJ_UNIT_8 91 // UNIT_8
#define OBJ_UNIT_9 92 // UNIT_9
#define OBJ_UPDATESTATECHARGE_VAL 3 // UPDATESTATECHARGE_VAL
#define OBJ_UPDATESTATECHARGE_VAL_1 80 // UPDATESTATECHARGE_VAL_1
#define OBJ_VALIDLED_1 21 // VALIDLED_1
#define OBJ_VALIDLED_10 100 // VALIDLED_10
#define OBJ_VALIDLED_2 24 // VALIDLED_2
#define OBJ_VALIDLED_3 25 // VALIDLED_3
#define OBJ_VALIDLED_4 26 // VALIDLED_4
#define OBJ_VALIDLED_5 27 // VALIDLED_5
#define OBJ_VALIDLED_6 28 // VALIDLED_6
#define OBJ_VALIDLED_7 29 // VALIDLED_7
#define OBJ_VALIDLED_8 98 // VALIDLED_8
#define OBJ_VALIDLED_9 99 // VALIDLED_9
#define OBJ_VOLT_LVL_VAL_1 1 // VOLT_LVL_VAL_1

// Attribute list
#define ATTR_INVERTED                0x00000001		// Attribute inverted
#define ATTR_BLINKING                0x00000002		// Attribute blinking
#define ATTR_UNDERLINED              0x00000004		// Attribute underlined
#define ATTR_VISIBLE                 0x00000008		// Attribute visible
#define ATTR_TRANSPARENT             0x00000010		// Attribute transparent
#define ATTR_SMOOTH                  0x00000020		// Attribute smooth
#define ATTR_NOMINAL                 0x00000100		// Attribute nominal
#define ATTR_LOWER_BLINK_FG          0x00000200		// Attribute lower foreground blink
#define ATTR_UPPER_BLINK_FG          0x00000400		// Attribute upper foreground blink
#define ATTR_LOWER_BLINK_BK          0x00000800		// Attribute lower background blink
#define ATTR_UPPER_BLINK_BK          0x00001000		// Attribute upper background blink
#define ATTR_GRAB_FOCUS              0x00002000		// Attribute grab focus
#define ATTR_UPDATE_ON_EDIT          0x00004000		// Attribute update on edit
#define ATTR_ANIMATED                0x00008000		// Attribute animated
#define ATTR_ALIGN_CENTER            0x00010000		// Attribute align center
#define ATTR_ALIGN_RIGHT_BOTTOM      0x00020000		// Attribute align right bottom
#define ATTR_TEXTFLOW_RIGHT_TO_LEFT  0x00040000		// Attribute drawmode right to left
#define ATTR_TEXTFLOW_TOP_TO_BOTTOM  0x00080000		// Attribute drawmode top to bottom

#if (__GNUC__ > 4)
#define DRAWMODE_DEPRECATED(x)  __attribute__ ((deprecated(x)))
#else
#define DRAWMODE_DEPRECATED(x)  __attribute__ ((deprecated))
#endif

static const uint32_t ATTR_DRAWMODE_TOP_TO_BOTTOM DRAWMODE_DEPRECATED("Use ATTR_TEXTFLOW_RIGHT_TO_LEFT") = 0x00040000;
static const uint32_t ATTR_DRAWMODE_RIGHT_TO_LEFT DRAWMODE_DEPRECATED("Use ATTR_TEXTFLOW_TOP_TO_BOTTOM") = 0x00080000;
#endif
