#-----------------------------------------------
# srclist.mk
# This file is automatically generated, don't try to edit it
# all modifications will be lost with next build
#-----------------------------------------------
ARCH := arm
TARGET = PIXEL_TST_BAT
BASEBOARD := G327
# Listing C/C++ source files here. (C dependencies are automatically generated.)
SRC += .\cgen\__GS_driverapi.c 
SRC += .\cgen\MCQ_dev.c 
SRC += .\cgen\RCColor.c 
SRC += .\cgen\RCText.c 
SRC += .\cgen\gdsPrjUserCInfo_CM.c 
SRC += .\cgen\gdsPrjUserCInfo_VR.c 
SRC += PIXEL_TST_BAT.c 
SRC += AKB_Ctrl.c 
SRC += EngineInv_Ctrl.c 
SRC += MCM_Ctrl.c 
SRC += MAIN_Thread.c 
SRC += .\src\VechleIcons.c 
SRC += .\src\VertBar.c 
SRC += .\SIMULATION\simul.c 
SRC += Hyd_Inv_Ctrl.c 
SRC += .\src\J1939\j1939.c 
SRC += .\src\J1939\Spn.c 
# Debug options
FLAG_DEBUG = 0
FLAG_WINSIMU = 1
# Listing additional object files here.
ADDOBJ = 
LIBS = CanOpenSlaveStack-DSeriesS fpgaS gsGuiObjS iniS logS mbedcryptoS mbedtlsS mbedx509S gsNetwork-sslS gsThreadS UserCAPIS gsUtilS 
LIBDIRS = 
