/**-----------------------------------------------
 * gdsPrjUserCInfo_VR.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

#include <gdsPrjUserCInfo.h>

/* ----- Variable info ----- */
const tGsVarInfo _gs_prjusercinfo_mVarInfo[] =
{
    {.mHandle = 1, .mName = "Voltage_Level", .mComment = ""},
    {.mHandle = 2, .mName = "Ignition_Is_On", .mComment = ""},
    {.mHandle = 3, .mName = "Disch_Pwr", .mComment = ""},
    {.mHandle = 4, .mName = "Current", .mComment = ""},
    {.mHandle = 5, .mName = "FastUpdCharg", .mComment = ""},
    {.mHandle = 6, .mName = "Hi_Cell_Volt", .mComment = ""},
    {.mHandle = 7, .mName = "Low_Cell_Volt", .mComment = ""},
    {.mHandle = 8, .mName = "Discharge_Cap", .mComment = ""},
    {.mHandle = 9, .mName = "AvDisPow_LED_1", .mComment = ""},
    {.mHandle = 10, .mName = "AvDisPow_LED_2", .mComment = ""},
    {.mHandle = 11, .mName = "AvDisPow_LED_3", .mComment = ""},
    {.mHandle = 12, .mName = "AvDisPow_LED_4", .mComment = ""},
    {.mHandle = 13, .mName = "AvDisPow_LED_5", .mComment = ""},
    {.mHandle = 14, .mName = "AvDisPow_LED_6", .mComment = ""},
    {.mHandle = 15, .mName = "AvDisPow_LED_7", .mComment = ""},
    {.mHandle = 16, .mName = "portA_0", .mComment = "Created by copy/paste object"},
    {.mHandle = 17, .mName = "Duty_5p", .mComment = ""},
    {.mHandle = 18, .mName = "BAT_DISCHARG_BAR", .mComment = "Created by copy/paste object"},
    {.mHandle = 19, .mName = "IcoIndx_10", .mComment = "Created by copy/paste object"},
    {.mHandle = 20, .mName = "IcoIndx_24", .mComment = "Created by copy/paste object"},
    {.mHandle = 21, .mName = "IcoIndx_12", .mComment = "Created by copy/paste object"},
    {.mHandle = 22, .mName = "IcoIndx_13", .mComment = "Created by copy/paste object"},
    {.mHandle = 23, .mName = "IcoIndx_14", .mComment = "Created by copy/paste object"},
    {.mHandle = 24, .mName = "IcoIndx_15", .mComment = "Created by copy/paste object"},
    {.mHandle = 25, .mName = "IcoIndx_16", .mComment = "Created by copy/paste object"},
    {.mHandle = 26, .mName = "IcoIndx_17", .mComment = "Created by copy/paste object"},
    {.mHandle = 27, .mName = "IcoIndx_18", .mComment = "Created by copy/paste object"},
    {.mHandle = 28, .mName = "IcoIndx_19", .mComment = "Created by copy/paste object"},
    {.mHandle = 29, .mName = "IcoIndx_20", .mComment = "Created by copy/paste object"},
    {.mHandle = 30, .mName = "IcoIndx_21", .mComment = "Created by copy/paste object"},
    {.mHandle = 31, .mName = "IcoIndx_22", .mComment = "Created by copy/paste object"},
    {.mHandle = 32, .mName = "IcoIndx_23", .mComment = "Created by copy/paste object"},
    {.mHandle = 33, .mName = "IcoIndx_11", .mComment = ""},
    {.mHandle = 34, .mName = "Trans_Speed", .mComment = "Created by copy/paste object"},
    {.mHandle = 35, .mName = "Trans_Rpm", .mComment = "Created by copy/paste object"},
    {.mHandle = 36, .mName = "Trans_Press", .mComment = "Created by copy/paste object"},
    {.mHandle = 37, .mName = "Trans_Fuel", .mComment = "Created by copy/paste object"},
    {.mHandle = 38, .mName = "INVERTER_ON", .mComment = ""},
    {.mHandle = 39, .mName = "INVERTER_ERROR", .mComment = ""},
    {.mHandle = 40, .mName = "INVERTER_WARN", .mComment = ""},
    {.mHandle = 41, .mName = "INVERTER_OVER_TEMP", .mComment = ""},
    {.mHandle = 42, .mName = "INVERTER_TORQUE", .mComment = "Реализованный момент вращения"},
    {.mHandle = 43, .mName = "INVERTER_RPM", .mComment = "Текущая частота вращения"},
    {.mHandle = 44, .mName = "INVERTER_CURRENT", .mComment = "Ток статора"},
    {.mHandle = 45, .mName = "INVERTER_POWER", .mComment = "Мощность, знаковая,"},
    {.mHandle = 46, .mName = "INVERTER_VOLTAGE", .mComment = "Напряжение ЗПТ,"},
    {.mHandle = 47, .mName = "BAT_LOW_LEVEL", .mComment = ""},
    {.mHandle = 48, .mName = "INV_LOW_LEVEL", .mComment = ""},
    {.mHandle = 49, .mName = "INV_READY", .mComment = ""},
    {.mHandle = 50, .mName = "AKB_AVLBL", .mComment = ""},
    {.mHandle = 51, .mName = "INV_VOLT_BAR", .mComment = ""},
    {.mHandle = 52, .mName = "INV_CURRENT_BAR", .mComment = ""},
    {.mHandle = 53, .mName = "BAT_CURRENT_BAR", .mComment = ""},
    {.mHandle = 65524, .mName = "SYS_U_SUPPLY", .mComment = ""},
    {.mHandle = 65525, .mName = "SYS_ENC_RIGHT", .mComment = ""},
    {.mHandle = 65526, .mName = "SYS_ENC_LEFT", .mComment = ""},
    {.mHandle = 65527, .mName = "SYS_TEMPERATURE", .mComment = ""},
    {.mHandle = 65528, .mName = "SYS_PRIORITY", .mComment = ""},
    {.mHandle = 65529, .mName = "SYS_COLOR", .mComment = ""},
    {.mHandle = 65530, .mName = "SYS_LANGUAGE", .mComment = ""},
    {.mHandle = 65531, .mName = "SYS_OPERATING_TIME", .mComment = ""}
};
const size_t _gs_prjusercinfo_mVarInfoSize = 61;

