/**-----------------------------------------------
 * gdsPrjUserCInfo_CM.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

#include <gdsPrjUserCInfo.h>

/* ----- Container info ----- */
const tGsContInfo _gs_prjusercinfo_mContInfo[] =
{
    {.mName = "VelcheIcons_1", .mNumber = 0},
    {.mName = "DashCont", .mNumber = 1},
    {.mName = "Container2", .mNumber = 2},
    {.mName = "ContParam", .mNumber = 3},
    {.mName = "Container4", .mNumber = 4}
};
const size_t _gs_prjusercinfo_mContInfoSize = 5;

/* ----- Mask info ----- */
const tGsMaskInfo _gs_prjusercinfo_mMaskInfo[] =
{
    {.mName = "0", .mNumber = 0},
    {.mName = "Mask1", .mNumber = 1},
    {.mName = "DashBoard", .mNumber = 2},
    {.mName = "Mask_PARAM", .mNumber = 3},
    {.mName = "WorkSite", .mNumber = 4}
};
const size_t _gs_prjusercinfo_mMaskInfoSize = 5;

