
/**-----------------------------------------------
 * RCText.h
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next project saving
 *
 * for access to texts from this resource use the symbols
 * only. Do not use the magic numbers !
 * The defines are changed to the resource base address at download
 *
 * Note: To use these 2 functions you have to check "Transfer all texts"
 *       in "Edit / Setup" in Text-Resourec-Dialog and to include
 *       "RCText.h" in your C-file!
 **-----------------------------------------------*/

#ifndef _RCTEXT_H_
#define _RCTEXT_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

/**-----------------------------------------------
 * RCTextGetText
 *
 * Retrieves a text from the text resource
 *
 * @param offset:  offset into the resource text table. Use offset
 *                 symbols "RCTEXT_T_..." from below to access
 * @param lngIdx:  Language index
 *                 Use GetVar(HDL_SYS_LANGUAGE) here
 *------------------------------------------------*/
const char* RCTextGetText(uint32_t offset, uint32_t lngIdx);

#ifdef __cplusplus
}
#endif

#define RCTEXT_CNT_G 1  // groups
#define RCTEXT_CNT_GT_DEFAULT 1  // group texts
#define RCTEXT_CNT_T 1  // texts (all together)
#define RCTEXT_CNT_L 0  // lists

/*
  Now the offsets to be used for above functions
  RCTextGetText(..) and RCTextGetListElement(..)
*/
#define RCTEXT_T_DEFAULT 289888		// Default (Default)

#endif  //_RCTEXT_H_

